

logging:
  file: /${project.name}/logs/postgres.log
  level:
    com:
      river:
        postgres:
          mapper: DEBUG
project:
  name: postgres
server:
  port: 8078
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=murugar&characterEncoding=UTF-8&useSSL=false
    username: postgres
    password: 123456
    druid:
      #初始化连接大小
      initial-size: 8
      #最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 10
      #查询超时时间
      query-timeout: 6000
      #事务查询超时时间
      transaction-query-timeout: 6000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800
      filters: stat,config
  jackson:
    time-zone: GMT+8

swagger:
  # 是否启用swagger，默认：true
  enabled: true
  # 标题
  title: PostgreSql RESTful API
  contact:
    # 维护人
    name: River
    email: 20207075@qq.com
    url: https://www.river.io
  # 版本
  version: 1.0.1
  # 描述
  description:
  # swagger扫描的基础包，默认：全扫描
  base-package: com.river.postgre
  # 需要处理的基础URL规则，默认：/**
  base-path: /**
  # 需要排除的URL规则，默认：空
  #  exclude-path: ""
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto