server:
  port: 8888
  servlet:
    context-path: /demo
  ssl:
    key-alias: tomcat
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
  tomcat:
    uri-encoding: utf-8
spring:
  thymeleaf:
    prefix: classpath:/templates/
